# Generated by Django 5.1.1 on 2024-10-01 16:44

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/', verbose_name='3D модель'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='product_thumbnails/', verbose_name='Миниатюра'),
        ),
    ]
