# Generated by Django 5.1.1 on 2024-10-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.productvariant'),
        ),
    ]
