# Generated by Django 5.1.1 on 2024-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmodel', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
